# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'GoogleAds-IMA-iOS-SDK', '~> 3.14.5'
  pod 'GSPlayer'
end
